CREATE DATABASE Teste_Usuario
GO

USE TESTE_USUARIO
GO

/*CRIA플O DE TABELAS*/
CREATE TABLE USUARIO(
	IDUSUARIO INT IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY(1,1),
	NUMERO VARCHAR(14),
	TIPO CHAR(3),
	ID_USUARIO INT
)
GO

CREATE TABLE HIST_USUARIO_NOVO(
	IDHISTORICO INT IDENTITY(1,1),
	NOME VARCHAR(50),
	SEXO CHAR(1),
	NUMERO VARCHAR(14),
	TIPO CHAR(3),
	USU_DATA DATETIME
)
GO



/*CRIA플O DA CHAVES PRIMARIAS*/
ALTER TABLE USUARIO ADD CONSTRAINT PK_IDUSUARIO
PRIMARY KEY (IDUSUARIO)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT PK_IDTELEFONE
PRIMARY KEY (IDTELEFONE)
GO

ALTER TABLE HIST_USUARIO_NOVO ADD CONSTRAINT PK_IDHISTORICO
PRIMARY KEY (IDHISTORICO)
GO

/*CRIA플O DE CHAVES ESTRANGEIRAS*/
ALTER TABLE TELEFONE ADD CONSTRAINT FK_USUARIO_TELEFONE
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(IDUSUARIO)
GO

/*CRIA플O DE REGRAS*/
ALTER TABLE USUARIO ADD CONSTRAINT CK_SEXO
CHECK(SEXO IN('M','F'))
GO

ALTER TABLE TELEFONE ADD CONSTRAINT CK_TIPO
CHECK(TIPO IN ('CEL','RES','COM'))
GO

/*PROCEDURES*/
CREATE PROC PROC_I_Usuario(
	@NOME VARCHAR(30),
	@SEXO CHAR(1),
	@NUMERO VARCHAR(14),
	@TIPO CHAR(3)
)
AS
DECLARE @FK INT
INSERT USUARIO VALUES(@NOME, @SEXO)

SET @FK=(SELECT IDUSUARIO FROM USUARIO WHERE IDUSUARIO = @@IDENTITY)

INSERT TELEFONE VALUES(@NUMERO,@TIPO,@FK)
GO
CREATE TRIGGER trg_historico
ON dbo.TELEFONE FOR INSERT
AS 
BEGIN
	DECLARE @NOME VARCHAR(50)
	DECLARE @SEXO CHAR(1)
	DECLARE @NUMERO VARCHAR(14)
	DECLARE @TIPO CHAR(3)
	DECLARE @DATA DATETIME

	SELECT @NOME =NOME FROM USUARIO
	SELECT @SEXO= SEXO FROM USUARIO
	SELECT @NUMERO= NUMERO FROM inserted
	SELECT @TIPO= TIPO FROM inserted

	SET @DATA= GETDATE()

	INSERT INTO HIST_USUARIO_NOVO VALUES(@NOME,@SEXO,@NUMERO,@TIPO,@DATA)
END
GO

CREATE PROC PROC_S_USUARIO
AS
SELECT U.NOME,U.SEXO,T.NUMERO,T.TIPO
FROM USUARIO U 
INNER JOIN TELEFONE T
ON U.IDUSUARIO= T.ID_USUARIO
GO

SELECT * FROM HIST_USUARIO_NOVO

/*EXECU합ES*/
EXEC PROC_I_Usuario 'Felipe','M','943422345','CEL'
GO

EXEC PROC_S_USUARIO
GO

